name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-24"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTVmNDQyZjQtYzUxNC00YzQ0LWE1YWMtM2MxNWEwNGM3N2M5IiwidGVuYW50X2lkIjoiZjFlMGNhMDRiOTMzOGJiYzUyZjgzNmM4NTE5Mzg0OGEyODBiM2I2ZDdkZjhhMTAxNTFkYjFhYTA1YzYyMTNhMSIsImludGVybmFsX3NlY3JldCI6IjY0OTYxMjNlLTJjZmItNGViNi1hYzhkLTJmZTc0ZTU2ZDhiOCJ9.J6EdVNpq7erCqdQy911IZzkASaeytr9Q9Yp2W7bxElk"
JWT_SECRET="jwtsecret"